# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-25 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SunFaLongCRM', '0003_auto_20190425_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='nid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='SunFaLongCRM.CustomerInfo'),
        ),
    ]
