# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-25 17:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SunFaLongCRM', '0004_auto_20190425_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
